### PR TITLE
Fix -Watimport-in-framework-header

### LINKED ISSUE #722: Error when using CocoaAsyncSocket as a framework in Xcode 11.4
There's an `@import Foundation;` statement in `CocoaAsyncSocket.h`. This causes build failures in Xcode 11.4 when importing CocoaAsyncSocket as a framework (e.g. with Carthage):

```
▸ Compiling RoutingHTTPServer.m

❌  /Users/runner/runners/2.170.1/work/1/s/Carthage/Build/iOS/CocoaAsyncSocket.framework/Headers/CocoaAsyncSocket.h:9:1: use of '@import' in framework header is discouraged, including this header requires -fmodules [-Werror,-Watimport-in-framework-header]

@import Foundation;
^



❌  /Users/runner/runners/2.170.1/work/1/s/WebDriverAgentLib/Vendor/RoutingHTTPServer/RoutingHTTPServer.h:20:9: could not build module 'CocoaAsyncSocket'

#import <CocoaAsyncSocket/GCDAsyncSocket.h>
 ~~~~~~~^
```

[This is because in Xcode 11.4, the `-Watimport-in-framework-header` warning is on by default](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes?language=objc)

### PR DESCRIPTION
**Pull request by qmfrederik**
As per https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes?language=objc

Fixes #722

### CODE REVIEW

**Comment by robbiehanson** [comment]
From Apple's Release Notes:

> Xcode 11.4 turns the -Watimport-in-framework-header warning on by default. Using @import in framework headers is discouraged, because doing so requires all importers to use modules.

So is Apple saying we should be using this ??? :
```objective-c
#import <Foundation/Foundation.h>
```

**Comment by mykola-mokhnach** [comment]
this is the original llvm PR: https://reviews.llvm.org/rC335780

File: Source/CocoaAsyncSocket.h [hunk 1]
```diff
@@ -6,7 +6,12 @@
 //  CocoaAsyncSocket project is in the public domain.
 //
 
+#if __has_feature(modules)
+#if __has_warning("-Watimport-in-framework-header")
+#pragma clang diagnostic ignored "-Watimport-in-framework-header"
+#endif
 @import Foundation;
+#endif
```
Comment (chrisballinger) [inline Source/CocoaAsyncSocket.h:14]:
```suggestion
#import <Foundation/Foundation.h>
```

Echoing what @robbiehanson said, I think the correct fix is to just not use `@import`
